name: Deploy

on:
  push:
    tags:
      - "**"

permissions:
  contents: write

env: 
  CARGO_TERM_COLOR: always

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # You can add more, for any target you'd like!
        include:
          - build: linux-x64
            target: x86_64-unknown-linux-musl
          - build: linux-aarch64
            target: aarch64-unknown-linux-musl
          - build: linux-armv7
            target: armv7-unknown-linux-musleabihf
          - build: linux-armv6
            target: arm-unknown-linux-musleabihf

    steps:
      - uses: actions/checkout@v4
      - name: Get the release version from the tag
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Restore Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: artifacts
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.target }}
          args: "--locked --release"
          strip: true

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/dropprs
          asset_name: dropprs-${{ matrix.target }}
          tag: ${{ github.ref }}