name: Deploy

on:
  push:
    tags:
      - "**"

permissions:
  contents: write

env: 
  CARGO_TERM_COLOR: always

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # You can add more, for any target you'd like!
        include:
          - build: linux-x64
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - build: linux-aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v4
      - name: Get the release version from the tag
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Restore Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: artifacts

      - name: Build
        run: cargo build --verbose --release --target ${{ matrix.target }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./target/${{ matrix.target }}/release/dropprs
